services:
  - type: web
    name: nwh-rma
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run nwh_rma_app.py --server.port=$PORT --server.address=0.0.0.0"
    plan: free